// Code generated by "stringer -type=WireBit"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ORIGIN-0]
	_ = x[VERTICAL-1]
	_ = x[HORIZONTAL-2]
	_ = x[INTERSECTION-3]
}

const _WireBit_name = "ORIGINVERTICALHORIZONTALINTERSECTION"

var _WireBit_index = [...]uint8{0, 6, 14, 24, 36}

func (i WireBit) String() string {
	if i < 0 || i >= WireBit(len(_WireBit_index)-1) {
		return "WireBit(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _WireBit_name[_WireBit_index[i]:_WireBit_index[i+1]]
}
